/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";
import type { GetWebsitesAnalyticsTrackingQueryResponse, GetWebsitesAnalyticsTracking401, GetWebsitesAnalyticsTracking403, GetWebsitesAnalyticsTracking429, GetWebsitesAnalyticsTracking500 } from "../types/GetWebsitesAnalyticsTracking.js";

function getGetWebsitesAnalyticsTrackingUrl() {
  const res = { method: 'GET', url: `/websites/analytics/tracking` as const }  
  return res
}

/**
 * @description Site token OBRIGATÓRIO (identifica o tenant). Envia-se via header `x-site-token` (preferido) ou `Authorization: Bearer <site token>`. O site usa o par para injectar `<script defer src="{src}" data-website-id="{websiteId}">`. Devolve 204 (sem corpo) quando o tenant não tem website de analytics ou o Umami não está configurado no servidor. Qualquer parâmetro do pedido é ignorado — o tenant vem só do site token.
 * @summary Obter o par websiteId + src do script de tracking do tenant
 * {@link /websites/analytics/tracking}
 */
export async function getWebsitesAnalyticsTracking(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetWebsitesAnalyticsTrackingQueryResponse, ResponseErrorConfig<GetWebsitesAnalyticsTracking401 | GetWebsitesAnalyticsTracking403 | GetWebsitesAnalyticsTracking429 | GetWebsitesAnalyticsTracking500>, unknown>({ method : "GET", url : getGetWebsitesAnalyticsTrackingUrl().url.toString(), ... requestConfig })  
  return res.data
}