/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Par de tracking do tenant (cache privada de 5 minutos).
*/
export type GetWebsitesAnalyticsTracking200 = {
    /**
     * @type string, uuid
    */
    websiteId: string;
    /**
     * @type string
    */
    src: string;
};

/**
 * @description Sem tracking disponível para este tenant (sem corpo).
*/
export type GetWebsitesAnalyticsTracking204 = any;

/**
 * @description Site token em falta
*/
export type GetWebsitesAnalyticsTracking401 = any;

/**
 * @description Site token inválido ou revogado
*/
export type GetWebsitesAnalyticsTracking403 = any;

/**
 * @description Demasiados pedidos
*/
export type GetWebsitesAnalyticsTracking429 = any;

/**
 * @description Erro interno
*/
export type GetWebsitesAnalyticsTracking500 = any;

export type GetWebsitesAnalyticsTrackingQueryResponse = (GetWebsitesAnalyticsTracking200 | GetWebsitesAnalyticsTracking204);

export type GetWebsitesAnalyticsTrackingQuery = {
    Response: GetWebsitesAnalyticsTracking200 | GetWebsitesAnalyticsTracking204;
    Errors: GetWebsitesAnalyticsTracking401 | GetWebsitesAnalyticsTracking403 | GetWebsitesAnalyticsTracking429 | GetWebsitesAnalyticsTracking500;
};